name: ngobrel_contacts
description: A Flutter plugin to retrieve and manage contacts on Android and iOS devices based on contacts_service by Clovis Nicolas
version: 0.0.2
author: Ngobrel <chat@ngobrel.rocks>
homepage: https://github.com/ngobrel/ngobrel-contacts
maintainer: Ngobrel

environment:
  sdk: ">=2.0.0-dev.58.0.flutter-f981f09760 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: flutter.plugins.ngobrel.contacts
    pluginClass: ContactsPlugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0
